package com.careerguidance.service.impl;
import com.careerguidance.dto.request.*; import com.careerguidance.dto.response.*; import com.careerguidance.entity.*; import com.careerguidance.exception.*; import com.careerguidance.repository.*; import com.careerguidance.service.MentorVerificationService; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.*; import java.util.*; import java.util.stream.*;
@Service @Transactional public class MentorVerificationServiceImpl implements MentorVerificationService {
 private final UserRepository users; private final RoleRepository roles; private final MentorProfileRepository profiles; private final MentorVerificationLogRepository logs; private final PasswordEncoder encoder;
 public MentorVerificationServiceImpl(UserRepository u,RoleRepository r,MentorProfileRepository p,MentorVerificationLogRepository l,PasswordEncoder e){users=u;roles=r;profiles=p;logs=l;encoder=e;}
 public MessageResponse register(MentorRegistrationRequest r){ if(users.existsByEmail(r.getEmail())) throw new BadRequestException("Email is already in use"); if(r.getDocuments().stream().map(d->d.documentType.toUpperCase()).noneMatch(t->t.contains("GOVERNMENT"))||r.getDocuments().stream().map(d->d.documentType.toUpperCase()).noneMatch(t->t.contains("PROFESSIONAL"))||r.getDocuments().stream().map(d->d.documentType.toUpperCase()).noneMatch(t->t.contains("RESUME"))) throw new BadRequestException("Government ID, professional ID and resume are required"); String[] names=r.getFullName().trim().split("\\s+",2); User u=new User();u.setFirstName(names[0]);u.setLastName(names.length>1?names[1]:"");u.setEmail(r.getEmail().toLowerCase());u.setPassword(encoder.encode(r.getPassword()));u.setPhone(r.getPhone());u.setAccountStatus(AccountStatus.PENDING_VERIFICATION);u.setRoles(Set.of(roles.findByName(RoleName.MENTOR).orElseThrow(()->new BadRequestException("MENTOR role missing"))));users.save(u); MentorProfile p=new MentorProfile();p.setUser(u);p.setBio(r.getBio());p.setCompany(r.getCompany());p.setJobTitle(r.getJobTitle());p.setExperienceYears(r.getExperienceYears());p.setExpertise(r.getExpertise());p.setLinkedinUrl(r.getLinkedinUrl());p.setGithubUrl(r.getGithubUrl());p.setPortfolioUrl(r.getPortfolioUrl()); for(var d:r.getDocuments()){MentorDocument x=new MentorDocument();x.setMentor(p);x.setDocumentType(d.documentType);x.setFileUrl(d.fileUrl);p.getDocuments().add(x);if(d.documentType.toUpperCase().contains("RESUME"))p.setResumeUrl(d.fileUrl);} profiles.save(p); log(p,"SUBMITTED",null,null); System.out.println("Mentor application submitted: "+u.getEmail()); return new MessageResponse("Your mentor application has been submitted successfully and is awaiting administrator verification."); }
 public List<MentorProfileResponse> pending(){return profiles.findByVerificationStatus(AccountStatus.PENDING_VERIFICATION).stream().map(this::response).toList();} public MentorProfileResponse detail(Long id){return response(profile(id));}
 public MessageResponse approve(Long id,String email){MentorProfile p=profile(id);User a=admin(email);p.getUser().setAccountStatus(AccountStatus.VERIFIED);p.setVerificationStatus(AccountStatus.VERIFIED);p.setVerifiedAt(LocalDateTime.now());p.setVerifiedBy(a);p.getDocuments().forEach(d->{d.setVerificationStatus(AccountStatus.VERIFIED);d.setVerifiedAt(LocalDateTime.now());d.setVerifiedBy(a);});log(p,"APPROVED",a,null);System.out.println("Mentor approved: "+p.getUser().getEmail());return new MessageResponse("Mentor approved successfully");}
 public MessageResponse reject(Long id,RejectionRequest r,String email){MentorProfile p=profile(id);User a=admin(email);p.getUser().setAccountStatus(AccountStatus.REJECTED);p.setVerificationStatus(AccountStatus.REJECTED);p.getDocuments().forEach(d->{d.setVerificationStatus(AccountStatus.REJECTED);d.setRemarks(r.getRemarks());});log(p,"REJECTED",a,r.getRemarks());System.out.println("Mentor rejected: "+p.getUser().getEmail());return new MessageResponse("Mentor rejected successfully");}
 public Map<String,Long> statistics(){return Map.of("totalMentors",users.countByRoles_Name(RoleName.MENTOR),"pendingVerification",profiles.countByVerificationStatus(AccountStatus.PENDING_VERIFICATION),"verifiedMentors",profiles.countByVerificationStatus(AccountStatus.VERIFIED),"rejectedMentors",profiles.countByVerificationStatus(AccountStatus.REJECTED));}
 private MentorProfile profile(Long id){return profiles.findById(id).orElseThrow(()->new ResourceNotFoundException("Mentor profile not found"));} private User admin(String e){return users.findByEmail(e).orElseThrow(()->new UnauthorizedException("Administrator not found"));} private void log(MentorProfile p,String action,User a,String remarks){MentorVerificationLog l=new MentorVerificationLog();l.setMentor(p);l.setAction(action);l.setAdmin(a);l.setRemarks(remarks);logs.save(l);} private MentorProfileResponse response(MentorProfile p){User u=p.getUser();return new MentorProfileResponse(p.getId(),u.getId(),u.getFirstName()+" "+u.getLastName(),u.getEmail(),u.getPhone(),p.getCompany(),p.getJobTitle(),p.getExperienceYears(),p.getExpertise(),p.getBio(),p.getLinkedinUrl(),p.getGithubUrl(),p.getPortfolioUrl(),p.getVerificationStatus(),u.getCreatedAt(),p.getVerifiedAt(),p.getDocuments().stream().map(d->new MentorProfileResponse.Document(d.getId(),d.getDocumentType(),d.getFileUrl())).toList());}
}
