import { useEffect, useMemo, useState } from 'react';
import { motion } from 'framer-motion';
import { useNavigate } from 'react-router-dom';
import { BookOpen, Search } from 'lucide-react';
import AppLayout from '../../components/layout/AppLayout';
import api from '../../services/api';

const categoryTone = value => {
  const name = (value || '').toLowerCase();
  if (name.includes('technical')) return { icon: 'bg-blue-600', border: 'border-blue-200', pill: 'bg-blue-100 text-blue-700', button: 'bg-blue-600 hover:bg-blue-700' };
  if (name.includes('aptitude')) return { icon: 'bg-violet-600', border: 'border-violet-200', pill: 'bg-violet-100 text-violet-700', button: 'bg-violet-600 hover:bg-violet-700' };
  if (name.includes('personality')) return { icon: 'bg-rose-600', border: 'border-rose-200', pill: 'bg-rose-100 text-rose-700', button: 'bg-rose-600 hover:bg-rose-700' };
  if (name.includes('soft') || name.includes('communication')) return { icon: 'bg-teal-600', border: 'border-teal-200', pill: 'bg-teal-100 text-teal-700', button: 'bg-teal-600 hover:bg-teal-700' };
  return { icon: 'bg-amber-500', border: 'border-amber-200', pill: 'bg-amber-100 text-amber-700', button: 'bg-amber-500 hover:bg-amber-600' };
};
const difficultyTone = value => ({ EASY: 'bg-emerald-100 text-emerald-700', MEDIUM: 'bg-amber-100 text-amber-700', HARD: 'bg-rose-100 text-rose-700', EXPERT: 'bg-fuchsia-100 text-fuchsia-700' }[(value || '').toUpperCase()] || 'bg-slate-100 text-slate-700');

export default function AssessmentCategories() {
  const navigate = useNavigate(); const [assessments, setAssessments] = useState([]); const [query, setQuery] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  useEffect(() => { api.get('/api/assessment/published').then(({ data }) => setAssessments(data || [])).catch(() => setError('Unable to load published assessments.')).finally(() => setLoading(false)); }, []);
  const visible = useMemo(() => assessments.filter(item => `${item.title} ${item.description} ${item.category} ${item.difficulty}`.toLowerCase().includes(query.toLowerCase())), [assessments, query]);
  const open = assessment => navigate('/assessments/details', { state: { assessment: { title: assessment.title, description: assessment.description, category: assessment.category, difficulty: assessment.difficulty, duration: `${assessment.durationMinutes} minutes`, questions: assessment.totalQuestions, passingScore: assessment.passingPercentage, maxAttempts: assessment.maximumAttempts, instructions: assessment.instructions, id: assessment.id } } });
  return <AppLayout><div className="space-y-7"><header><p className="text-xs font-bold uppercase tracking-widest text-blue-600">Assessment Engine</p><h1 className="mt-1 text-2xl font-extrabold text-slate-900 sm:text-3xl">Available Assessments</h1><p className="mt-1 text-sm text-slate-500">Only assessments published by your administrator are shown here.</p></header>
    <label className="relative block max-w-md"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" /><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search available assessments..." className="w-full rounded-xl border border-slate-200 bg-white py-2.5 pl-10 pr-4 text-sm outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100" /></label>
    {loading ? <div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{[1, 2, 3].map(id => <div key={id} className="h-72 animate-pulse rounded-2xl bg-slate-100" />)}</div> : error ? <p className="rounded-xl bg-rose-50 p-4 text-sm font-medium text-rose-700">{error}</p> : visible.length === 0 ? <div className="rounded-2xl border border-dashed border-slate-300 bg-white p-12 text-center"><BookOpen className="mx-auto text-slate-300" size={36} /><h2 className="mt-3 font-bold text-slate-700">No published assessments</h2><p className="mt-1 text-sm text-slate-500">Your administrator has not published an assessment yet.</p></div> : <><p className="text-sm text-slate-500"><b className="text-slate-800">{visible.length}</b> assessment{visible.length === 1 ? '' : 's'} available</p><div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{visible.map((assessment, index) => { const tone = categoryTone(assessment.category); return <motion.article key={assessment.id} initial={{ opacity: 0, y: 14 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: index * 0.04 }} className={`rounded-2xl border ${tone.border} bg-white p-5 shadow-card transition hover:-translate-y-0.5 hover:shadow-card-md`}><div className="flex items-start justify-between gap-3"><div className={`grid h-12 w-12 place-items-center rounded-2xl ${tone.icon} text-white shadow-sm`}><BookOpen size={22} /></div><div className="flex flex-col items-end gap-1"><span className={`rounded-full px-3 py-1 text-xs font-bold ${tone.pill}`}>{assessment.category}</span><span className={`rounded-full px-3 py-1 text-xs font-bold ${difficultyTone(assessment.difficulty)}`}>{assessment.difficulty}</span></div></div><h2 className="mt-5 font-extrabold leading-snug text-slate-900">{assessment.title}</h2><p className="mt-2 line-clamp-2 min-h-10 text-sm leading-relaxed text-slate-500">{assessment.description || 'No description provided.'}</p><p className="mt-4 flex items-center gap-1 text-xs font-semibold text-slate-500"><BookOpen size={13} />{assessment.totalQuestions} questions · {assessment.durationMinutes} min</p><button onClick={() => open(assessment)} className={`mt-5 w-full rounded-xl py-2.5 text-sm font-bold text-white shadow-sm transition ${tone.button}`}>View Assessment</button></motion.article>; })}</div></>}</div></AppLayout>;
}
