import { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { CheckCircle2, XCircle, ListChecks } from 'lucide-react';
import AppLayout from '../../components/layout/AppLayout';
import api from '../../services/api';

export default function PublishedAssessmentResult() {
  const { attemptId } = useParams(); const navigate = useNavigate(); const [result, setResult] = useState(null); const [review, setReview] = useState(false); const [error, setError] = useState('');
  useEffect(() => { api.get(`/api/assessment/published/attempts/${attemptId}/result`).then((response) => setResult(response.data)).catch((requestError) => setError(requestError.response?.data?.message || 'Unable to load this result.')); }, [attemptId]);
  if (error) return <AppLayout><p className="mx-auto max-w-3xl rounded-xl bg-red-50 p-5 text-red-700">{error}</p></AppLayout>; if (!result) return <AppLayout><p className="p-6 text-slate-500">Loading result…</p></AppLayout>;
  return <AppLayout><main className="mx-auto max-w-4xl space-y-6"><section className={`rounded-2xl p-7 text-white ${result.passed ? 'bg-emerald-600' : 'bg-amber-600'}`}><p className="text-sm font-bold uppercase tracking-wider">Assessment result</p><h1 className="mt-1 text-3xl font-black">{result.percentage.toFixed(1)}%</h1><p className="mt-2">{result.passed ? 'Passed — great work!' : 'Not passed this time. Review the answers and try again.'}</p></section><section className="grid gap-4 sm:grid-cols-3">{[['Correct', result.correctAnswers, 'text-emerald-600'], ['Incorrect', result.wrongAnswers, 'text-rose-600'], ['Skipped', result.skippedAnswers, 'text-slate-600']].map(([label, value, color]) => <div key={label} className="rounded-2xl bg-white p-5 text-center shadow-card"><p className={`text-3xl font-black ${color}`}>{value}</p><p className="text-sm text-slate-500">{label}</p></div>)}</section><div className="flex gap-3"><button onClick={() => setReview(!review)} className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-5 py-3 text-sm font-bold text-white"><ListChecks size={16}/>{review ? 'Hide review' : 'Review correct answers'}</button><button onClick={() => navigate('/assessments/history')} className="rounded-xl border px-5 py-3 text-sm font-bold">View history</button></div>{review && <section className="space-y-4">{result.review.map((item, index) => <article key={item.questionId} className="rounded-2xl border bg-white p-5"><div className="flex gap-2"><span className="font-bold">{index + 1}.</span><div><p className="font-bold">{item.questionText}</p><p className={`mt-3 text-sm font-semibold ${item.correct ? 'text-emerald-700' : 'text-rose-700'}`}>{item.correct ? <CheckCircle2 className="mr-1 inline" size={15}/> : <XCircle className="mr-1 inline" size={15}/>}Your answer: {item.selectedOption || 'Not answered'}</p>{!item.correct && <p className="mt-1 text-sm font-semibold text-emerald-700">Correct answer: {item.correctOption}</p>}</div></div></article>)}</section>}</main></AppLayout>;
}
