export const assessmentSections = [
  {
    id: 'technical',
    title: 'Technical Skills',
    eyebrow: 'Section 1',
    description: 'Rate your current proficiency across key software skills.',
    type: 'rating',
    weight: 30,
  },
  {
    id: 'aptitude',
    title: 'Aptitude',
    eyebrow: 'Section 2',
    description: 'Answer practical reasoning, analytical, and numerical questions.',
    type: 'mcq',
    weight: 30,
  },
  {
    id: 'personality',
    title: 'Personality',
    eyebrow: 'Section 3',
    description: 'Share how you usually work, learn, and make decisions.',
    type: 'likert',
    weight: 20,
  },
  {
    id: 'interests',
    title: 'Interest Survey',
    eyebrow: 'Section 4',
    description: 'Choose career areas that genuinely interest you.',
    type: 'multi',
    weight: 20,
  },
];

export const ratingScale = [
  { value: 1, label: 'Beginner' },
  { value: 2, label: 'Basic' },
  { value: 3, label: 'Intermediate' },
  { value: 4, label: 'Advanced' },
  { value: 5, label: 'Expert' },
];

export const likertScale = [
  { value: 5, label: 'Strongly Agree' },
  { value: 4, label: 'Agree' },
  { value: 3, label: 'Neutral' },
  { value: 2, label: 'Disagree' },
  { value: 1, label: 'Strongly Disagree' },
];

export const assessmentQuestions = [
  ...['Java', 'Python', 'React', 'SQL', 'Spring Boot', 'HTML', 'CSS', 'JavaScript'].map((skill, index) => ({
    id: `technical-${index + 1}`,
    sectionId: 'technical',
    type: 'rating',
    title: `Rate your proficiency in ${skill}.`,
    skill,
    required: true,
    options: ratingScale,
  })),
  {
    id: 'aptitude-1',
    sectionId: 'aptitude',
    type: 'mcq',
    title: 'If all analysts are problem solvers and some problem solvers are programmers, which statement is definitely true?',
    category: 'Logical Reasoning',
    required: true,
    options: ['All programmers are analysts', 'Some analysts may be programmers', 'No analysts are programmers', 'All problem solvers are analysts'],
    correctAnswer: 'Some analysts may be programmers',
  },
  {
    id: 'aptitude-2',
    sectionId: 'aptitude',
    type: 'mcq',
    title: 'Find the next number in the series: 3, 6, 12, 24, 48, ?',
    category: 'Numerical Ability',
    required: true,
    options: ['72', '84', '96', '108'],
    correctAnswer: '96',
  },
  {
    id: 'aptitude-3',
    sectionId: 'aptitude',
    type: 'mcq',
    title: 'A system fails only when both network and database services are down. Network is up. What can you infer?',
    category: 'Analytical Thinking',
    required: true,
    options: ['System must fail', 'System cannot fail due to both being down', 'Database must be up', 'Network must be down later'],
    correctAnswer: 'System cannot fail due to both being down',
  },
  {
    id: 'aptitude-4',
    sectionId: 'aptitude',
    type: 'mcq',
    title: 'Which action is best when a bug cannot be reproduced reliably?',
    category: 'Problem Solving',
    required: true,
    options: ['Ignore it', 'Add logging and isolate conditions', 'Rewrite the whole app', 'Ask users to avoid it'],
    correctAnswer: 'Add logging and isolate conditions',
  },
  {
    id: 'aptitude-5',
    sectionId: 'aptitude',
    type: 'mcq',
    title: 'If 20% of a class of 80 students choose AI, how many students is that?',
    category: 'Numerical Ability',
    required: true,
    options: ['8', '12', '16', '20'],
    correctAnswer: '16',
  },
  {
    id: 'aptitude-6',
    sectionId: 'aptitude',
    type: 'mcq',
    title: 'Choose the odd one out.',
    category: 'Logical Reasoning',
    required: true,
    options: ['React', 'Angular', 'Vue', 'MySQL'],
    correctAnswer: 'MySQL',
  },
  {
    id: 'aptitude-7',
    sectionId: 'aptitude',
    type: 'mcq',
    title: 'A product metric drops after a deployment. What should be checked first?',
    category: 'Analytical Thinking',
    required: true,
    options: ['Recent code and configuration changes', 'Office internet speed', 'Team attendance', 'Brand colors'],
    correctAnswer: 'Recent code and configuration changes',
  },
  {
    id: 'aptitude-8',
    sectionId: 'aptitude',
    type: 'mcq',
    title: 'Which data structure follows first-in, first-out behavior?',
    category: 'Problem Solving',
    required: true,
    options: ['Stack', 'Queue', 'Tree', 'Graph'],
    correctAnswer: 'Queue',
  },
  {
    id: 'aptitude-9',
    sectionId: 'aptitude',
    type: 'mcq',
    title: 'If A is greater than B and B is greater than C, which is true?',
    category: 'Logical Reasoning',
    required: true,
    options: ['C is greater than A', 'A is greater than C', 'A equals C', 'B is smallest'],
    correctAnswer: 'A is greater than C',
  },
  {
    id: 'aptitude-10',
    sectionId: 'aptitude',
    type: 'mcq',
    title: 'A task takes 6 hours for 3 people at equal speed. How long for 6 people?',
    category: 'Numerical Ability',
    required: true,
    options: ['2 hours', '3 hours', '6 hours', '12 hours'],
    correctAnswer: '3 hours',
  },
  {
    id: 'aptitude-11',
    sectionId: 'aptitude',
    type: 'mcq',
    title: 'Which is the clearest acceptance criterion?',
    category: 'Analytical Thinking',
    required: true,
    options: ['Make it better', 'Improve performance', 'Page loads in under 2 seconds for 95% of users', 'Use modern code'],
    correctAnswer: 'Page loads in under 2 seconds for 95% of users',
  },
  {
    id: 'aptitude-12',
    sectionId: 'aptitude',
    type: 'mcq',
    title: 'What is the best first step in solving a complex unknown problem?',
    category: 'Problem Solving',
    required: true,
    options: ['Define constraints and known facts', 'Pick a random solution', 'Wait for more time', 'Skip documentation'],
    correctAnswer: 'Define constraints and known facts',
  },
  {
    id: 'aptitude-13',
    sectionId: 'aptitude',
    type: 'mcq',
    title: 'If a model is accurate on training data but poor on new data, it likely has:',
    category: 'Analytical Thinking',
    required: true,
    options: ['Underfitting', 'Overfitting', 'Perfect generalization', 'No features'],
    correctAnswer: 'Overfitting',
  },
  {
    id: 'aptitude-14',
    sectionId: 'aptitude',
    type: 'mcq',
    title: 'Which SQL clause filters grouped results?',
    category: 'Problem Solving',
    required: true,
    options: ['WHERE', 'HAVING', 'ORDER BY', 'LIMIT'],
    correctAnswer: 'HAVING',
  },
  {
    id: 'aptitude-15',
    sectionId: 'aptitude',
    type: 'mcq',
    title: 'A 25% discount on 200 leaves a price of:',
    category: 'Numerical Ability',
    required: true,
    options: ['125', '150', '175', '180'],
    correctAnswer: '150',
  },
  ...[
    'I enjoy solving difficult problems.',
    'I prefer teamwork when building solutions.',
    'I like leading projects and coordinating people.',
    'I am comfortable learning new tools independently.',
    'I enjoy interpreting data to make decisions.',
    'I prefer structured tasks with clear milestones.',
    'I like creating visual experiences for users.',
    'I stay calm when debugging under pressure.',
  ].map((title, index) => ({
    id: `personality-${index + 1}`,
    sectionId: 'personality',
    type: 'likert',
    title,
    required: true,
    options: likertScale,
  })),
  {
    id: 'interests-1',
    sectionId: 'interests',
    type: 'multi',
    title: 'Select the domains you are most interested in exploring.',
    required: true,
    minSelections: 3,
    options: [
      'Artificial Intelligence',
      'Data Science',
      'Cyber Security',
      'Cloud Computing',
      'Mobile Development',
      'Game Development',
      'UI UX',
      'DevOps',
      'Business',
      'Digital Marketing',
    ],
  },
];

export const defaultCareerPreviews = [
  {
    title: 'Data Analyst',
    match: 92,
    description: 'Translate business questions into dashboards, models, and actionable insights.',
    skills: ['SQL', 'Python', 'Analytics'],
  },
  {
    title: 'AI Engineer',
    match: 88,
    description: 'Build intelligent systems using machine learning, APIs, and production workflows.',
    skills: ['Python', 'AI', 'Cloud'],
  },
  {
    title: 'Backend Developer',
    match: 84,
    description: 'Design reliable APIs, databases, and application services for product teams.',
    skills: ['Java', 'Spring Boot', 'SQL'],
  },
  {
    title: 'Cyber Security Analyst',
    match: 79,
    description: 'Monitor systems, investigate risks, and strengthen organizational security.',
    skills: ['Security', 'Networks', 'Analysis'],
  },
];
