import { useEffect, useMemo, useState } from 'react';
import { Search, UserCheck, UserX, UsersRound } from 'lucide-react';
import { adminService } from '../../services/adminService';

const Status = ({ children, tone = 'slate' }) => <span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${tone === 'green' ? 'bg-emerald-50 text-emerald-700' : tone === 'amber' ? 'bg-amber-50 text-amber-700' : tone === 'red' ? 'bg-rose-50 text-rose-700' : 'bg-slate-100 text-slate-600'}`}>{children}</span>;
const Empty = ({ text }) => <div className="p-12 text-center text-sm text-slate-500">{text}</div>;

function PageHeader({ eyebrow, title, description }) {
  return <header className="mb-7"><p className="text-sm font-semibold text-indigo-600">{eyebrow}</p><h1 className="mt-1 text-3xl font-bold">{title}</h1><p className="mt-2 text-slate-500">{description}</p></header>;
}
function SearchBox({ value, onChange }) { return <label className="relative block max-w-md"><Search className="absolute left-3 top-3 text-slate-400" size={18}/><input className="w-full rounded-xl border border-slate-200 py-2.5 pl-10 pr-3 text-sm outline-none focus:border-indigo-400" placeholder="Search records..." value={value} onChange={e => onChange(e.target.value)}/></label>; }

export function UserManagementPage() {
  const [users, setUsers] = useState([]), [query, setQuery] = useState(''), [loading, setLoading] = useState(true), [error, setError] = useState('');
  const load = async () => { setLoading(true); setError(''); try { const result = await adminService.getUsers({ search: query, size: 100 }); setUsers(result.content || result || []); } catch { setError('Unable to load users from the server.'); } finally { setLoading(false); } };
  useEffect(() => { const timer = setTimeout(load, 250); return () => clearTimeout(timer); }, [query]);
  const toggle = async (user) => { try { const updated = user.active ? await adminService.deactivateUser(user.id) : await adminService.activateUser(user.id); setUsers(rows => rows.map(row => row.id === user.id ? updated : row)); } catch { setError(`Unable to update ${user.email}.`); } };
  return <><PageHeader eyebrow="ACCOUNT ADMINISTRATION" title="Manage users" description="View real registered accounts and control whether they can access the platform."/>{error && <p className="mb-4 rounded-xl bg-rose-50 px-4 py-3 text-sm text-rose-700">{error}</p>}<section className="rounded-2xl border border-slate-100 bg-white p-5 shadow-sm"><SearchBox value={query} onChange={setQuery}/>{loading ? <Empty text="Loading registered users..."/> : users.length === 0 ? <Empty text="No users match your search."/> : <div className="mt-5 overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead className="border-y bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-4 py-3">User</th><th className="px-4 py-3">Roles</th><th className="px-4 py-3">Account</th><th className="px-4 py-3">Access</th><th className="px-4 py-3"></th></tr></thead><tbody>{users.map(user => <tr key={user.id} className="border-b border-slate-50"><td className="px-4 py-4"><p className="font-semibold">{user.firstName} {user.lastName}</p><p className="text-xs text-slate-500">{user.email}</p></td><td className="px-4 py-4">{user.roles?.join(', ') || '—'}</td><td className="px-4 py-4"><Status tone={user.accountStatus === 'REJECTED' ? 'red' : user.accountStatus?.includes('PENDING') ? 'amber' : 'green'}>{user.accountStatus}</Status></td><td className="px-4 py-4"><Status tone={user.active ? 'green' : 'slate'}>{user.active ? 'Active' : 'Disabled'}</Status></td><td className="px-4 py-4"><button onClick={() => toggle(user)} className={`inline-flex items-center gap-2 rounded-lg px-3 py-2 text-xs font-bold ${user.active ? 'bg-rose-50 text-rose-700 hover:bg-rose-100' : 'bg-emerald-50 text-emerald-700 hover:bg-emerald-100'}`}>{user.active ? <UserX size={15}/> : <UserCheck size={15}/>} {user.active ? 'Disable' : 'Enable'}</button></td></tr>)}</tbody></table></div>}</section></>;
}

export function MentorManagementPage() {
  const [mentors, setMentors] = useState([]), [query, setQuery] = useState(''), [loading, setLoading] = useState(true), [error, setError] = useState('');
  const load = async () => { setLoading(true); setError(''); try { setMentors(await adminService.getMentors()); } catch { setError('Unable to load mentors from the server.'); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const visible = useMemo(() => mentors.filter(mentor => JSON.stringify(mentor).toLowerCase().includes(query.toLowerCase())), [mentors, query]);
  const toggle = async (mentor) => { const active = mentor.active !== false; try { await (active ? adminService.deactivateMentor(mentor.id) : adminService.activateMentor(mentor.id)); await load(); } catch { setError(`Unable to update ${mentor.fullName}.`); } };
  return <><PageHeader eyebrow="MENTOR ADMINISTRATION" title="Manage mentors" description="Manage every mentor account and see each verification result. Pending applications are reviewed in Mentor verification."/>{error && <p className="mb-4 rounded-xl bg-rose-50 px-4 py-3 text-sm text-rose-700">{error}</p>}<section className="rounded-2xl border border-slate-100 bg-white p-5 shadow-sm"><SearchBox value={query} onChange={setQuery}/>{loading ? <Empty text="Loading mentor accounts..."/> : visible.length === 0 ? <Empty text="No mentors match your search."/> : <div className="mt-5 overflow-x-auto"><table className="w-full min-w-[800px] text-left text-sm"><thead className="border-y bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-4 py-3">Mentor</th><th className="px-4 py-3">Company & role</th><th className="px-4 py-3">Verification</th><th className="px-4 py-3">Access</th><th className="px-4 py-3">Experience</th><th className="px-4 py-3"></th></tr></thead><tbody>{visible.map(mentor => <tr key={mentor.id} className="border-b border-slate-50"><td className="px-4 py-4"><p className="font-semibold">{mentor.fullName}</p><p className="text-xs text-slate-500">{mentor.email}</p></td><td className="px-4 py-4 text-slate-600">{mentor.company || '—'}<span className="block text-xs text-slate-400">{mentor.jobTitle || '—'}</span></td><td className="px-4 py-4"><Status tone={mentor.status === 'VERIFIED' ? 'green' : mentor.status === 'REJECTED' ? 'red' : 'amber'}>{mentor.status}</Status></td><td className="px-4 py-4"><Status tone={mentor.active ? 'green' : 'slate'}>{mentor.active ? 'Active' : 'Disabled'}</Status></td><td className="px-4 py-4">{mentor.experienceYears ?? '—'} years</td><td className="px-4 py-4"><button onClick={() => toggle(mentor)} className={`inline-flex items-center gap-2 rounded-lg px-3 py-2 text-xs font-bold ${mentor.active ? 'bg-rose-50 text-rose-700 hover:bg-rose-100' : 'bg-emerald-50 text-emerald-700 hover:bg-emerald-100'}`}><UsersRound size={15}/>{mentor.active ? 'Disable' : 'Enable'}</button></td></tr>)}</tbody></table></div>}</section></>;
}
