import { useEffect, useMemo, useState } from 'react';
import { FiCheck, FiExternalLink, FiFileText, FiSearch, FiX } from 'react-icons/fi';
import { mentorVerificationService as service } from '../../services/mentorVerificationService';

const toneFor = type => type?.toLowerCase().includes('government')
  ? 'border-rose-200 bg-rose-50 text-rose-700 hover:border-rose-400 hover:bg-rose-100'
  : type?.toLowerCase().includes('professional')
    ? 'border-violet-200 bg-violet-50 text-violet-700 hover:border-violet-400 hover:bg-violet-100'
    : 'border-teal-200 bg-teal-50 text-teal-700 hover:border-teal-400 hover:bg-teal-100';

export default function MentorVerificationPage() {
  const [applications, setApplications] = useState([]); const [query, setQuery] = useState('');
  const [selected, setSelected] = useState(null); const [remarks, setRemarks] = useState('');
  const [rejecting, setRejecting] = useState(false); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  const load = () => { setLoading(true); setError(''); service.list().then(data => setApplications(data || [])).catch(() => setError('Unable to load mentor applications.')).finally(() => setLoading(false)); };
  useEffect(load, []);
  const visible = useMemo(() => applications.filter(item => JSON.stringify(item).toLowerCase().includes(query.toLowerCase())), [applications, query]);
  const decide = async approved => { if (!approved && !remarks.trim()) return; setSaving(true); try { if (approved) await service.approve(selected.id); else await service.reject(selected.id, remarks.trim()); setSelected(null); setRejecting(false); setRemarks(''); load(); } catch { setError(`Unable to ${approved ? 'approve' : 'reject'} this application.`); } finally { setSaving(false); } };
  return <div className="mx-auto max-w-7xl"><header className="mb-7 rounded-3xl bg-gradient-to-r from-slate-900 to-slate-700 px-6 py-7 text-white sm:px-8"><p className="text-sm font-bold tracking-wider text-teal-300">ADMIN · MENTOR VERIFICATION</p><h1 className="mt-2 text-3xl font-extrabold">Review mentor applications</h1><p className="mt-2 text-sm text-slate-300">Open the submitted Google Drive links, verify the real documents, then decide access.</p></header>
    {error && <p className="mb-5 rounded-xl bg-rose-50 px-4 py-3 text-sm font-medium text-rose-700">{error}</p>}
    <section className="rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-col gap-4 border-b border-slate-100 p-5 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-bold text-slate-900">Pending applications</h2><p className="text-sm text-slate-500">{applications.length} application{applications.length === 1 ? '' : 's'} awaiting a decision</p></div><label className="relative w-full sm:w-72"><FiSearch className="absolute left-3 top-3 text-slate-400" /><input className="w-full rounded-xl border border-slate-200 py-2.5 pl-10 pr-3 text-sm outline-none focus:border-teal-500" placeholder="Search applications" value={query} onChange={event => setQuery(event.target.value)} /></label></div>
      {loading ? <div className="space-y-3 p-5">{[1, 2, 3].map(item => <div key={item} className="h-20 animate-pulse rounded-xl bg-slate-100" />)}</div> : visible.length === 0 ? <div className="p-12 text-center"><FiFileText className="mx-auto text-slate-300" size={34} /><p className="mt-3 font-semibold text-slate-700">No pending mentor applications</p></div> : <div className="divide-y divide-slate-100">{visible.map(application => <article key={application.id} className="flex flex-col gap-4 p-5 lg:flex-row lg:items-center"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="font-bold text-slate-900">{application.fullName}</h3><span className="rounded-full bg-amber-100 px-2.5 py-1 text-xs font-bold text-amber-800">PENDING REVIEW</span></div><p className="mt-1 text-sm text-slate-500">{application.email} · {application.company} · {application.jobTitle}</p><p className="mt-2 text-xs text-slate-500">{application.experienceYears} years experience · {application.documents?.length || 0} Drive link(s)</p></div><button onClick={() => setSelected(application)} className="rounded-xl border border-slate-300 px-4 py-2 text-sm font-bold text-slate-700 hover:bg-slate-50">Review application</button></article>)}</div>}</section>
    {selected && <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/50 p-4" role="dialog" aria-modal="true"><div className="max-h-[90vh] w-full max-w-3xl overflow-y-auto rounded-3xl bg-white shadow-2xl"><div className="flex items-start justify-between border-b border-slate-100 p-6"><div><p className="text-xs font-bold tracking-wider text-teal-600">APPLICATION REVIEW</p><h2 className="mt-1 text-2xl font-extrabold text-slate-900">{selected.fullName}</h2><p className="mt-1 text-sm text-slate-500">{selected.email}</p></div><button onClick={() => setSelected(null)} className="rounded-lg p-2 text-slate-500 hover:bg-slate-100"><FiX size={20} /></button></div><div className="p-6"><div className="grid gap-4 rounded-2xl bg-slate-50 p-5 sm:grid-cols-2"><Detail label="Company" value={selected.company} /><Detail label="Job title" value={selected.jobTitle} /><Detail label="Experience" value={`${selected.experienceYears} years`} /><Detail label="Phone" value={selected.phone || 'Not provided'} /><Detail label="Expertise" value={selected.expertise || 'Not provided'} /><Detail label="Submitted" value={selected.submittedAt ? new Date(selected.submittedAt).toLocaleDateString() : '—'} /></div><h3 className="mt-7 font-bold text-slate-900">Google Drive verification links</h3><p className="mt-1 text-sm text-slate-500">Open each document before approving. Access must be set to “Anyone with the link can view”.</p><div className="mt-3 grid gap-3 sm:grid-cols-3">{selected.documents?.map(document => <a key={document.id} href={document.fileUrl} target="_blank" rel="noreferrer" className={`rounded-xl border p-4 text-sm font-semibold transition ${toneFor(document.type)}`}><FiFileText className="mb-2" size={20} />{document.type}<span className="mt-2 flex items-center gap-1 text-xs text-slate-500">Open Drive link <FiExternalLink /></span></a>)}</div>{selected.bio && <><h3 className="mt-7 font-bold text-slate-900">Bio</h3><p className="mt-2 text-sm leading-6 text-slate-600">{selected.bio}</p></>}<div className="mt-8 flex flex-col-reverse gap-3 border-t border-slate-100 pt-5 sm:flex-row sm:justify-end"><button onClick={() => setRejecting(true)} disabled={saving} className="rounded-xl border border-rose-300 px-5 py-2.5 text-sm font-bold text-rose-700 hover:bg-rose-50">Reject application</button><button onClick={() => decide(true)} disabled={saving} className="inline-flex items-center justify-center gap-2 rounded-xl bg-emerald-600 px-5 py-2.5 text-sm font-bold text-white hover:bg-emerald-700"><FiCheck />{saving ? 'Saving…' : 'Approve mentor'}</button></div></div></div></div>}
    {rejecting && <div className="fixed inset-0 z-[60] grid place-items-center bg-slate-950/60 p-4"><div className="w-full max-w-md rounded-2xl bg-white p-6 shadow-2xl"><h2 className="text-xl font-bold text-slate-900">Reject application</h2><textarea className="mt-4 w-full rounded-xl border border-slate-300 p-3 text-sm" rows="4" value={remarks} onChange={event => setRemarks(event.target.value)} placeholder="Reason for rejection" /><div className="mt-5 flex justify-end gap-3"><button onClick={() => setRejecting(false)} className="rounded-xl px-4 py-2 text-sm font-bold text-slate-600">Cancel</button><button onClick={() => decide(false)} disabled={saving || !remarks.trim()} className="rounded-xl bg-rose-600 px-4 py-2 text-sm font-bold text-white disabled:opacity-50">{saving ? 'Saving…' : 'Confirm rejection'}</button></div></div></div>}
  </div>;
}
function Detail({ label, value }) { return <div><p className="text-xs font-bold uppercase tracking-wide text-slate-400">{label}</p><p className="mt-1 text-sm text-slate-800">{value}</p></div>; }
