package com.careerguidance.controller;
import com.careerguidance.dto.request.UpdateStudentRequest; import com.careerguidance.dto.response.*; import com.careerguidance.entity.*; import com.careerguidance.exception.ResourceNotFoundException; import com.careerguidance.repository.UserRepository; import jakarta.validation.Valid; import org.springframework.data.domain.*; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/admin/students") @PreAuthorize("hasRole('ADMIN')") public class StudentManagementController {private final UserRepository users;public StudentManagementController(UserRepository u){users=u;}private StudentSummaryResponse out(User u){return new StudentSummaryResponse(u.getId(),u.getFirstName(),u.getLastName(),u.getEmail(),u.getCollegeName(),u.getCgpa(),u.getActive());}private User find(Long id){return users.findById(id).orElseThrow(()->new ResourceNotFoundException("Student not found: "+id));}
 @GetMapping public Page<StudentSummaryResponse> all(@RequestParam(defaultValue="") String search,@RequestParam(defaultValue="0") int page,@RequestParam(defaultValue="20") int size,@RequestParam(defaultValue="createdAt") String sort){String field=java.util.Set.of("createdAt","firstName","email","cgpa").contains(sort)?sort:"createdAt";return users.findByRoles_NameAndEmailContainingIgnoreCase(RoleName.STUDENT,search,PageRequest.of(page,Math.min(size,100),Sort.by(field).descending())).map(this::out);}
 @GetMapping("/{id}") public StudentSummaryResponse one(@PathVariable Long id){return out(find(id));}
 @PutMapping("/{id}") public StudentSummaryResponse update(@PathVariable Long id,@Valid @RequestBody UpdateStudentRequest r){User u=find(id);u.setFirstName(r.getFirstName());u.setLastName(r.getLastName());u.setEmail(r.getEmail());u.setPhone(r.getPhone());u.setCgpa(r.getCgpa());u.setCollegeName(r.getCollegeName());return out(users.save(u));}
 @PatchMapping("/{id}/activate") public StudentSummaryResponse activate(@PathVariable Long id){User u=find(id);u.setActive(true);return out(users.save(u));}
 @PatchMapping("/{id}/deactivate") public StudentSummaryResponse deactivate(@PathVariable Long id){User u=find(id);u.setActive(false);return out(users.save(u));}
 @DeleteMapping("/{id}") public org.springframework.http.ResponseEntity<Void> delete(@PathVariable Long id){users.delete(find(id));return org.springframework.http.ResponseEntity.noContent().build();}}
